import "dotenv/config";
import readline from "node:readline";
import { pathToFileURL } from "node:url";
import { parseUrineClinicalResultString } from "./serial_urine_analyzer_parser.js";

function log(message, extra = "") {
    console.log(`[SERIAL-URINE-EMU] ${message}${extra ? ` ${extra}` : ""}`);
}

function normalizeBoolean(value, defaultValue = false) {
    if (value === undefined || value === null || value === "") {
        return defaultValue;
    }
    return String(value).trim().toLowerCase() === "true";
}

function pad2(value) {
    return String(value).padStart(2, "0");
}

function formatDate(date = new Date()) {
    return `${date.getFullYear()}-${pad2(date.getMonth() + 1)}-${pad2(date.getDate())}`;
}

function formatTime(date = new Date()) {
    return `${pad2(date.getHours())}:${pad2(date.getMinutes())}:${pad2(date.getSeconds())}`;
}

function formatLotDate(date = new Date()) {
    const oneYearLater = new Date(date);
    oneYearLater.setFullYear(oneYearLater.getFullYear() + 1);
    return formatDate(oneYearLater);
}

function buildBarcodeLikePatientId(sequenceNo, date = new Date()) {
    const year = String(date.getFullYear()).slice(-2);
    const month = pad2(date.getMonth() + 1);
    const day = pad2(date.getDate());
    const typziad = process.env.SERIAL_URINE_EMULATOR_TYPZIAD || "A";
    return `${year}${month}${day}${typziad}${String(sequenceNo).padStart(4, "0")}`;
}

function pickBySequence(values, sequenceNo) {
    return values[(Math.max(sequenceNo, 1) - 1) % values.length];
}

function buildObservations(sequenceNo) {
    const specificGravity = (1.005 + ((sequenceNo - 1) % 20) * 0.001).toFixed(3);
    const acidity = (5 + ((sequenceNo - 1) % 35) * 0.1).toFixed(1);

    return [
        { code: "GLU", value: pickBySequence(["Neg", "Trace", "Pos"], sequenceNo), mark: "" },
        { code: "BIL", value: pickBySequence(["Neg", "Pos"], sequenceNo), mark: "" },
        { code: "KET", value: pickBySequence(["Neg", "Trace", "Small", "Moderate"], sequenceNo), mark: "" },
        { code: "SG", value: specificGravity, mark: "" },
        { code: "BLO", value: pickBySequence(["Neg", "Trace", "Small"], sequenceNo), mark: "" },
        { code: "pH", value: acidity, mark: "" },
        { code: "PRO", value: pickBySequence(["Neg", "Trace", "Pos"], sequenceNo), mark: "" },
        { code: "URO", value: pickBySequence(["Norm", "17", "33"], sequenceNo), mark: "" },
        { code: "NIT", value: pickBySequence(["Neg", "Pos"], sequenceNo), mark: "" },
        { code: "LEU", value: pickBySequence(["Neg", "Trace", "Small", "Moderate", "Large"], sequenceNo), mark: "" },
    ];
}

function buildEmulatorLine({ sequenceNo, patientId, patientName }) {
    const now = new Date();
    const color = pickBySequence(["Yellow", "Light Yellow", "Amber"], sequenceNo);
    const clarity = pickBySequence(["Clear", "Slightly Cloudy", "Cloudy"], sequenceNo);
    const observations = buildObservations(sequenceNo);
    const fields = [
        String(sequenceNo),
        formatDate(now),
        formatTime(now),
        process.env.SERIAL_URINE_EMULATOR_INSTRUMENT_SERIAL || "EMU-CLINITEK-001",
        patientId,
        patientName,
        "",
        "",
        process.env.SERIAL_URINE_EMULATOR_OPERATOR_ID || "EMU01",
        process.env.SERIAL_URINE_EMULATOR_STRIP_TYPE || "Multistix 10 SG",
        color,
        clarity,
    ];

    for (const observation of observations) {
        fields.push(observation.code, observation.value, observation.mark);
    }

    fields.push(
        process.env.SERIAL_URINE_EMULATOR_STRIP_LOT || "EMU-LOT-001",
        formatLotDate(now),
        process.env.SERIAL_URINE_EMULATOR_NOTE || "Generated by serial emulator"
    );

    return fields.join(",");
}

async function getSerialPortClass() {
    const serialportModule = await import("serialport").catch(() => null);
    if (!serialportModule?.SerialPort) {
        throw new Error('Package "serialport" is not installed. Run npm install to enable the Clinitek emulator.');
    }

    return serialportModule.SerialPort;
}

async function writeLineToSerialPort(rawLine) {
    const SerialPort = await getSerialPortClass();
    const portPath = process.env.SERIAL_URINE_EMULATOR_COM_PORT?.trim() || process.env.SERIAL_URINE_COM_PORT?.trim();
    if (!portPath) {
        throw new Error("SERIAL_URINE_EMULATOR_COM_PORT is not configured.");
    }

    const baudRate = Number(process.env.SERIAL_URINE_EMULATOR_BAUD_RATE || process.env.SERIAL_URINE_BAUD_RATE || 9600);
    const dataBits = Number(process.env.SERIAL_URINE_EMULATOR_DATA_BITS || process.env.SERIAL_URINE_DATA_BITS || 8);
    const stopBits = Number(process.env.SERIAL_URINE_EMULATOR_STOP_BITS || process.env.SERIAL_URINE_STOP_BITS || 1);
    const parity = process.env.SERIAL_URINE_EMULATOR_PARITY || process.env.SERIAL_URINE_PARITY || "none";

    log("Opening emulator COM port", JSON.stringify({ portPath, baudRate, dataBits, stopBits, parity }));

    const port = new SerialPort({
        path: portPath,
        baudRate,
        dataBits,
        stopBits,
        parity,
        autoOpen: true,
    });

    await new Promise((resolve, reject) => {
        port.once("open", resolve);
        port.once("error", reject);
    });

    await new Promise((resolve, reject) => {
        port.write(`${rawLine}\r`, (error) => {
            if (error) {
                reject(error);
                return;
            }

            port.drain((drainError) => {
                if (drainError) {
                    reject(drainError);
                    return;
                }

                resolve();
            });
        });
    });

    await new Promise((resolve) => {
        port.close(() => resolve());
    });
}

function printPreview(rawLine) {
    const parsed = parseUrineClinicalResultString(rawLine);
    log("Emulator raw line", rawLine);
    log("Parsed preview", JSON.stringify({
        patientId: parsed.patientId,
        patientName: parsed.patientName,
        color: parsed.color,
        clarity: parsed.clarity,
        observations: parsed.observations.map((item) => ({
            code: item.code,
            value: item.value,
        })),
    }));
}

async function emitSample({ sequenceNo, patientId, patientName, printOnly = false }) {
    const rawLine = buildEmulatorLine({ sequenceNo, patientId, patientName });
    printPreview(rawLine);

    if (printOnly) {
        log("Print-only mode enabled. Nothing was sent to COM.");
        return;
    }

    await writeLineToSerialPort(rawLine);
    log("Sample sent to COM", patientId);
}

async function startInteractiveMode(printOnly = false) {
    const rl = readline.createInterface({
        input: process.stdin,
        output: process.stdout,
        terminal: true,
    });

    let sequenceNo = Number(process.env.SERIAL_URINE_EMULATOR_START_SEQUENCE || 1);
    const defaultPatientName = process.env.SERIAL_URINE_EMULATOR_PATIENT_NAME || "TEST CLINITEK";

    log('Interactive mode. Enter patient barcode, or press Enter for auto-generated one. Type "exit" to quit.');

    const ask = () =>
        new Promise((resolve) => {
            rl.question("patientId> ", resolve);
        });

    while (true) {
        const answer = String(await ask()).trim();
        if (["exit", "quit", "q"].includes(answer.toLowerCase())) {
            break;
        }

        const patientId = answer || buildBarcodeLikePatientId(sequenceNo);
        const patientName = defaultPatientName;

        try {
            await emitSample({
                sequenceNo,
                patientId,
                patientName,
                printOnly,
            });
            sequenceNo += 1;
        } catch (error) {
            log("Emulator send error", error instanceof Error ? error.message : String(error));
        }
    }

    rl.close();
}

async function startAutoMode(printOnly = false) {
    let sequenceNo = Number(process.env.SERIAL_URINE_EMULATOR_START_SEQUENCE || 1);
    const intervalMs = Number(process.env.SERIAL_URINE_EMULATOR_INTERVAL_MS || 5000);
    const patientName = process.env.SERIAL_URINE_EMULATOR_PATIENT_NAME || "TEST CLINITEK";

    log("Auto-send mode started", JSON.stringify({ intervalMs, printOnly }));

    while (true) {
        const patientId = buildBarcodeLikePatientId(sequenceNo);

        try {
            await emitSample({
                sequenceNo,
                patientId,
                patientName,
                printOnly,
            });
        } catch (error) {
            log("Auto-send error", error instanceof Error ? error.message : String(error));
        }

        sequenceNo += 1;
        await new Promise((resolve) => setTimeout(resolve, intervalMs));
    }
}

async function main() {
    const args = process.argv.slice(2);
    const flags = new Set(args.filter((item) => item.startsWith("--")));
    const positional = args.filter((item) => !item.startsWith("--"));
    const patientId = positional[0]?.trim();
    const patientName = positional.slice(1).join(" ").trim() || process.env.SERIAL_URINE_EMULATOR_PATIENT_NAME || "TEST CLINITEK";
    const printOnly = flags.has("--print-only") || normalizeBoolean(process.env.SERIAL_URINE_EMULATOR_PRINT_ONLY, false);
    const autoSend = flags.has("--auto") || normalizeBoolean(process.env.SERIAL_URINE_EMULATOR_AUTO_SEND, false);
    const sequenceNo = Number(process.env.SERIAL_URINE_EMULATOR_START_SEQUENCE || 1);

    if (autoSend) {
        await startAutoMode(printOnly);
        return;
    }

    if (patientId) {
        await emitSample({
            sequenceNo,
            patientId,
            patientName,
            printOnly,
        });
        return;
    }

    await startInteractiveMode(printOnly);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    main().catch((error) => {
        console.error(`[SERIAL-URINE-EMU] Fatal error: ${error instanceof Error ? error.message : String(error)}`);
        process.exitCode = 1;
    });
}
